#ifndef PARAMETERS_H
#define PARAMETERS_H

#define STEPS_OFFLINE 10000
#define STEPS_PER_REPETITION 5000
#define REPETITIONS_PER_GENERATION 2
#define QTY_FLOWERS 20
#define QTY_HIVES 5
#define QTY_BEES 10

#endif// PARAMETERS_H
